/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lidselecter;

import java.awt.Image;

/**
 *
 * @author chris
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        //this.setExtendedState(Main.MAXIMIZED_BOTH);
        //this.setIconImage(new ImageIcon("/Icon.png").getImage());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        overzichtSpelerButton = new javax.swing.JButton();
        locatieButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        agendaMasterclassButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        beherenToernooiButton = new javax.swing.JButton();
        agendaToernooiButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        beherenMasterclassButton = new javax.swing.JButton();
        beherenSpelerButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        overzichtSpelerButton.setText("Speler overzicht");
        overzichtSpelerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overzichtSpelerButtonActionPerformed(evt);
            }
        });

        locatieButton.setText("Locatie´s");
        locatieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locatieButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Locatie");

        agendaMasterclassButton.setText("Masterclass agenda");
        agendaMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaMasterclassButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Masterclass");

        beherenToernooiButton.setText("Toernooi beheer");
        beherenToernooiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beherenToernooiButtonActionPerformed(evt);
            }
        });

        agendaToernooiButton.setText("Toernooien agenda");
        agendaToernooiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaToernooiButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Toernooien");

        jLabel1.setText("Spelers");

        beherenMasterclassButton.setText("Masterclass beheren");
        beherenMasterclassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beherenMasterclassButtonActionPerformed(evt);
            }
        });

        beherenSpelerButton.setText("Speler beheer");
        beherenSpelerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beherenSpelerButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Inschrijfing betalen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(agendaMasterclassButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(beherenMasterclassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(locatieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(47, 47, 47))
                                .addComponent(agendaToernooiButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addComponent(beherenToernooiButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(overzichtSpelerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(beherenSpelerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beherenSpelerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overzichtSpelerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locatieButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agendaToernooiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beherenToernooiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agendaMasterclassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beherenMasterclassButton)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locatieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locatieButtonActionPerformed
        // TODO add your handling code here:        
        Locatie_main Locatie_main = new Locatie_main();
        Locatie_main.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_locatieButtonActionPerformed

    private void overzichtSpelerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overzichtSpelerButtonActionPerformed
        // TODO add your handling code here:       
        LedenOverzicht LedenOverzicht = new LedenOverzicht();
        LedenOverzicht.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_overzichtSpelerButtonActionPerformed

    private void agendaMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaMasterclassButtonActionPerformed
        // TODO add your handling code here:        
        Masterclass_main Masterclass_main = new Masterclass_main();
        Masterclass_main.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_agendaMasterclassButtonActionPerformed

    private void agendaToernooiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaToernooiButtonActionPerformed
        Toernooi_main toernooi = new Toernooi_main();
        toernooi.setVisible(rootPaneCheckingEnabled);
        toernooi.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_agendaToernooiButtonActionPerformed

    private void beherenSpelerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beherenSpelerButtonActionPerformed
        Ledeneditor ledenedit = new Ledeneditor();
        ledenedit.setVisible(rootPaneCheckingEnabled);
        ledenedit.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_beherenSpelerButtonActionPerformed

    private void beherenToernooiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beherenToernooiButtonActionPerformed
        // TODO add your handling code here:
        Toernooi_beheren toernooi = new Toernooi_beheren();
        toernooi.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_beherenToernooiButtonActionPerformed

    private void beherenSpelerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beherenSpelerButtonMouseEntered
        
    }//GEN-LAST:event_beherenSpelerButtonMouseEntered

    private void beherenMasterclassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beherenMasterclassButtonActionPerformed
        Masterclass_beheren Masterclass_beheren = new Masterclass_beheren();
        Masterclass_beheren.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_beherenMasterclassButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Toernooi_Betalen Toernooi_Betalen = new Toernooi_Betalen();
        Toernooi_Betalen.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendaMasterclassButton;
    private javax.swing.JButton agendaToernooiButton;
    private javax.swing.JButton beherenMasterclassButton;
    private javax.swing.JButton beherenSpelerButton;
    private javax.swing.JButton beherenToernooiButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton locatieButton;
    private javax.swing.JButton overzichtSpelerButton;
    // End of variables declaration//GEN-END:variables
}
