/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lidselecter;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;

/**
 *
 * @author Chris
 */
public class rating_overzicht extends javax.swing.JFrame {

    DefaultListModel spelerModel = new DefaultListModel();
    DefaultListModel toernooiModel = new DefaultListModel();
    int id;
    int spelerid;

    public rating_overzicht() {
        initComponents();
        speler.setModel(spelerModel);
        toernooi.setModel(toernooiModel);
        getLijst();
    }
    
    
        private void getLijst() {
        try {
            Sql_connect.doConnect();
            PreparedStatement stat2 = Sql_connect.getConnection().prepareStatement("select Naam, Id_toernooi from toernooi where Id_toernooi IN (select Id_toernooi from rating)");
            ResultSet result2 = stat2.executeQuery();
            toernooiModel.removeAllElements();
            while (result2.next()) {
                ModelItem item = new ModelItem();
                item.id = result2.getInt("Id_toernooi");
                item.naam = result2.getString("Naam");
                
                toernooiModel.addElement(item);
                
            }           
            
        } catch (Exception e) {
            //ePopup(e);
        }
    }
        
        private void getSelectedId() {
        try {
                ModelItem selectedItem = (ModelItem) toernooi.getSelectedValue();
                id = selectedItem.id;
                System.out.println(id);
                try {
                    Sql_connect.doConnect();
                    PreparedStatement stat2 = Sql_connect.getConnection().prepareStatement("select Voornaam, Achternaam, Id_persoon from persoon where Id_persoon IN (select Id_persoon from rating where Id_toernooi = ?)");
                    stat2.setInt(1, id);
                    ResultSet result2 = stat2.executeQuery();
                    spelerModel.removeAllElements();
                    while (result2.next()) {
                        ModelItem item = new ModelItem();
                        item.id = result2.getInt("Id_persoon");
                        item.voornaam = result2.getString("Voornaam");
                        item.achternaam = result2.getString("Achternaam");
                        spelerModel.addElement(item);
                    }           
                } catch (Exception e) {
                    //ePopup(e);
                }
        } catch (Exception e) {
            
        }

    }
        
                private void getSelectedSpeler() {
        try {
                ModelItem selectedItem = (ModelItem) speler.getSelectedValue();
                spelerid = selectedItem.id;
                System.out.println(id);
                try {
                    Sql_connect.doConnect();
                    PreparedStatement stat2 = Sql_connect.getConnection().prepareStatement("select behaalde_ronde, wijziging from rating where Id_persoon = ? AND Id_toernooi = ?");
                    stat2.setInt(1, spelerid);
                    stat2.setInt(2, id);
                    ResultSet result2 = stat2.executeQuery();
                    while (result2.next()) {
                        
                        ronde.setText(result2.getString("behaalde_ronde"));
                        rating.setText(result2.getString("wijziging"));
                        }           
                } catch (Exception e) {
                    //ePopup(e);
                }
        } catch (Exception e) {
            
        }

    }
        
    
    private void close() {
        this.dispose();
        Main menu = new Main();
        menu.setVisible(rootPaneCheckingEnabled);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        speler = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        toernooi = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        ronde = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Rating overzicht");

        speler.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        speler.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                spelerValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(speler);

        toernooi.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        toernooi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                toernooiValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(toernooi);

        jLabel1.setText("Behaalde ronde:");

        ronde.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel3.setText("Wijziging rating: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ronde, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ronde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Terug");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toernooiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_toernooiValueChanged
        getSelectedId();
    }//GEN-LAST:event_toernooiValueChanged

    private void spelerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_spelerValueChanged
        getSelectedSpeler();
    }//GEN-LAST:event_spelerValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rating_overzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rating_overzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rating_overzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rating_overzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rating_overzicht().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rating;
    private javax.swing.JLabel ronde;
    private javax.swing.JList speler;
    private javax.swing.JList toernooi;
    // End of variables declaration//GEN-END:variables
}
